### ISSUE TITLE
Player Login Error

### ISSUE THREAD

**Issue by ninmore** [ShepherdJerred/stAnalytics#2]
Whenever a player logs on to the server if they have logged in before this error will occur.

`[22:35:47] [Craft Scheduler Thread - 1357/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2a5e2f27-b0e1-42fb-8706-1eb7d1f41277-0' for key 'uuid'
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at sun.reflect.GeneratedConstructorAccessor261.newInstance(Unknown Source)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.shepherdjerred.stanalytics.mysql.QueryHelper.runUpdate(QueryHelper.java:46)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.shepherdjerred.stanalytics.mysql.QueryHelper.lambda$runAsyncUpdate$0(QueryHelper.java:33)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[22:35:47] [Craft Scheduler Thread - 1357/WARN]: 	at java.lang.Thread.run(Thread.java:745)`

Cheers

**Comment by ShepherdJerred** [comment]
What version is this

**Comment by ninmore** [comment]
2.0.0

**Comment by ShepherdJerred** [comment]
It's been fixed by https://github.com/ShepherdJerred/stAnalytics/commit/8bba9567b4ce9a167cf430e0f8b1a324c7794390 which will be included in a future release

**Comment by ShepherdJerred** [comment]
Actually no. I'm pretty sure I fixed this but I don't know if I pushed the commit, I'll look into it.

**Comment by ninmore** [comment]
Ok man.

**Comment by ShepherdJerred** [comment]
Can you set debug to true, and try to reproduce the error?

**Comment by ninmore** [comment]
Here you go. image as is formats better: [Image](http://bit.ly/2b6KC3d)

Raw text log:
`[22:49:39] [Craft Scheduler Thread - 1403/INFO]: [stAnalytics] HikariProxyPreparedStatement@1097692377 wrapping com.mysql.jdbc.JDBC42PreparedStatement@15aa3f: SELECT * from stanalytics_players WHERE uuid = '2a5e2f27-b0e1-42fb-8706-1eb7d1f41277' AND server = 'server1';
[22:49:39] [Craft Scheduler Thread - 1403/INFO]: [stAnalytics] Player has been here before
[22:49:39] [Craft Scheduler Thread - 1403/INFO]: [stAnalytics] HikariProxyPreparedStatement@1236040562 wrapping com.mysql.jdbc.JDBC42PreparedStatement@5e9c403: SELECT * from stanalytics_players WHERE uuid = '2a5e2f27-b0e1-42fb-8706-1eb7d1f41277' AND server = 'server1' AND day = 20 AND month = 8 AND year = 2016;
[22:49:39] [Craft Scheduler Thread - 1403/INFO]: [stAnalytics] Player hasn't been here today
[22:49:39] [Craft Scheduler Thread - 1406/INFO]: [stAnalytics] HikariProxyPreparedStatement@1033409310 wrapping com.mysql.jdbc.JDBC42PreparedStatement@35f15a50: INSERT INTO stanalytics_players VALUES ('server1',20,8,2016,7,'AquaDucky','2a5e2f27-b0e1-42fb-8706-1eb7d1f41277',0);
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2a5e2f27-b0e1-42fb-8706-1eb7d1f41277-0' for key 'uuid'
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at sun.reflect.GeneratedConstructorAccessor287.newInstance(Unknown Source)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.shepherdjerred.stanalytics.mysql.QueryHelper.runUpdate(QueryHelper.java:46)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.shepherdjerred.stanalytics.mysql.QueryHelper.lambda$runAsyncUpdate$0(QueryHelper.java:33)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[22:49:39] [Craft Scheduler Thread - 1406/WARN]: 	at java.lang.Thread.run(Thread.java:745)`

**Comment by ShepherdJerred** [comment]
Fixed in https://github.com/ShepherdJerred/stAnalytics/commit/097901ec865032faced95b0b8e11cc3ee1dde805
